### ISSUE TITLE
Data for testing MTMC

### ISSUE THREAD

**Issue by gemmact** [mcv-m6-video/class2019#10]
Hello,

in order to adapt our algorithm to the test sequences (S02 and S05, I understand), we would like to know which data will we have available for those sequences. Do we have the homography matrices? Or ground truth?

Thank you

**Comment by xavigiro** [comment]
Hi Gemma,

I just added the links to the test data on the slides, so you can directly check by yourselves.

I assume that when you refer to the homography matrices you are talking about the _calibration.txt_ that is available for each camera. You do have this, as in the train set.

The ground truth data is not available, as this is actually a competition, so it wouldn't make any sense if they released the solution :)

I hope you can manage to process these data.
