### ISSUE TITLE
Instructions for Week 2

### ISSUE THREAD

**Issue by xavigiro** [mcv-m6-video/class2019#2]
Find in [these slides](https://docs.google.com/presentation/d/1LZIe1vEVyIZ7RAWwobSYmUIwb7xVR0SmPQpZ4F2jPCc) the tasks for week 2.

**Comment by jrhupc** [comment]
Hi all,

Thanks to team 1 you can find the entire annotation to the Nvidia S03 - C010 sequence in the class2019 repository.  Please note that you will *not* use this files to evaluate your foreground segmentation but the ground truth provided by Nvidia in the zip file as we discussed in class.

Regards,
