### ISSUE TITLE
AP for object detection: Slides update and TensorFlow implementation

### ISSUE THREAD

**Issue by xavigiro** [mcv-m6-video/class2019#3]
Last week we realized there were different criteria when implementing average precision for object detection. 

The main one was how to deal with the case for which you do not have a confidence score for your detections, which was the case you obtained when detecting objects after a foreground substraction. In this case, we suggest that you assign random confidences scores to your detections, which will actually result in a random ranking when computing the PR curve. If you do this several times (eg. 10) and average the results, you will obtain valid estimation of AP.

In order to address other questions that arose while discussing after class with team 1, we have extended the description on how to compute AP for object detection in the [slides for week 1](https://docs.google.com/presentation/d/18bpZHpcEIZMwOHaFWCOcqLzQ3yQ3L848Kvv1_5a6UGA/edit?usp=sharing). We invite you to take a look at them and post your questions answering this thread.

The most important conclusion is that, in order to homogenize the APs you report, we suggest you use the [TensorFlow implementation](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/evaluation_protocols.md) of AP for object detection, inspired by the Pascal VOC challenge.

**Comment by pablorodriper** [comment]
Maybe you can calculate the AP between some files (for example: gt.txt and det_yolo3.txt) so we can check if our implementation is correct.
