### ISSUE TITLE
mAP for object tracking

### ISSUE THREAD

**Issue by gemmact** [mcv-m6-video/class2019#5]
Hi,

When evaluating object tracking, we are asked to give a mAP score for each method. Is this mAP obtained using the same method as for object detection? Or should we somehow take into account the id of the cars as well?

And, in case we do need to take the id into account, should we just make it coincide with the one we had in the previous frame for the same track? or should we somehow manage to first map all detected tracks to those in the groundtruth for then obtaining the mAP?

Thank you!

**Comment by xavigiro** [comment]
Hi Gemma,

thanks for sharing your question with us. If I understand well, this question is similar to the one also posed in class by one of your colleagues, and which motivated the later addition of the optional task 2.4.

In Tasks 2.1, 2.2, 2.3, the AP for each method is purely AP, so there is not ID to track. We discussed that, under this circumstance, the measured AP may be the same as in Task 1.1 or 1.2. However, I also pointed that you might want to correct the frame-based detections measured by AP, once you have detections linked across frames. For example, you may want to regularize the coordinates of the bounding boxes across frames, and this might result in an increase of performance in your AP.

If you are going to take the ID into account, then you are moving into Task 2.4. In that case, we suggest you use the suggested implementation of the IDF1 metric. You can explain in your report what this metric is, in addition to providing the value. You can also discuss about the pros & cons of this metric compared with others.

Is your question solved now ? If so, please close the issue.

Cheers !
